log_dir = "/mnt/data/st0x-rest-api/logs"
database_url = "sqlite:///mnt/data/st0x-rest-api/st0x.db"
registry_url = "https://raw.githubusercontent.com/ST0x-Technology/st0x.registry/4576454c0860c2bbf5726b3d1fcdc60771e377a7/registry"
rate_limit_global_rpm = 600
rate_limit_per_key_rpm = 60
docs_dir = "/var/lib/st0x-docs"
local_db_path = "/mnt/data/st0x-rest-api/raindex.db"
